[server]
host: 0.0.0.0
port: 7125
enable_debug_logging: True
config_path: ~/klipper_config

[authorization]
enabled: True
cors_domains:
    http://192.168.68.115
    http://192.168.68.118
    http://hevo.local
    *.local
    *.lan
    *://app.fluidd.xyz
trusted_clients:
    192.168.68.101
    192.168.68.0/24
    127.0.0.1
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128

[power Printer]
type: tplink_smartplug
address: 192.168.68.114
off_when_shutdown: True
locked_while_printing: True
restart_klipper_when_powered: True
restart_delay: 3

[update_manager]
client_repo: cadriel/fluidd
client_path: /home/pi/fluidd

[octoprint_compat]

[history]
